elasticsearch:
  cluster:
    name: elasticsearch
  address:
    host: localhost
    port: 9200
    username: 
    password: 
    ssl:
      enabled: false
      verification: false
spring:
  security:
    user:
      name: admin
      password: admin
      
dome:
  getproductofferingbyid: https://dome-marketplace.org/catalog/productOffering
  getproductspecificationbyid: https://dome-marketplace.org/catalog/productSpecification
  getservicespecificationbyid: https://dome-marketplace.org/service/serviceSpecification
  getresourcespecificationbyid: https://dome-marketplace.org/resource/resourceSpecification
  getallproductofferings: https://dome-marketplace.org/catalog/productOffering
  gettmfallproductofferings: https://dome-dev.eng.it/tmf-api/productCatalogManagement/v4/productOffering
  gettmfproductofferingbyid: https://dome-dev.eng.it/tmf-api/productCatalogManagement/v4/productOffering
  gettmfproductspecificationbyid: https://dome-dev.eng.it/tmf-api/productCatalogManagement/v4/productSpecification
  gettmfservicespecificationbyid: https://dome-dev.eng.it/tmf-api/serviceCatalogManagement/v4/serviceSpecification
  gettmfresourcespecificationbyid: https://dome-dev.eng.it/tmf-api/resourceCatalog/v4/resourceSpecification
  